name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/github-pages-deploy.yml'
      - 'tools/docSite/**'
      - '**/*.md'
      - '**/docs.json'

env:
  DOCS_BASE_URL: /
  DOCS_VERSIONING_DISABLE: 'true'
  OPEN_SOURCE_PUBLICATION: 'true'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: tools/docSite
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Corepack
        run: corepack enable

      - name: Setup yarn
        run: |
          yarn config set nodeLinker node-modules
          yarn config set enableImmutableInstalls false

      - run: yarn install
      - run: yarn setup
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}
          publish_dir: ./tools/docSite/build
