name: Packages

on:
  push:
    branches:
      - main
      - stable-v[0-9]+.x.x

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: release
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Corepack
        run: corepack enable

      - name: Setup yarn
        run: |
          yarn config set nodeLinker node-modules
          yarn config set enableImmutableInstalls false
          yarn config set npmPublishAccess public
          yarn config set npmPublishRegistry https://registry.npmjs.org/
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: yarn install
      - run: yarn build
      - run: yarn build:publish
      - run: yarn build:change-typings
      - run: yarn build:change-versions

      - name: Publish
        run: yarn publish:all
